services:
  grafana:
    volumes:
      - grafana-data:/var/lib/grafana

    networks:
      - monitoring
      - finpipe

networks:
  monitoring:
  finpipe:
    external: true
    name: finpipe-shared

volumes:
  grafana-data:
    name: monitoring_grafana-data
