class OwnerButtons:
    ADMIN_PANEL = "🛠️ Админка"
    USERS = "👥 Пользователи"
    STATISTICS = "📊 Статистика"
    ERRORS = "🚨 Ошибки"
    ADD_USER = "➕ Добавить пользователя"
    REMOVE_USER = "➖ Удалить пользователя"
    LIST_USERS = "📋 Список пользователей"
    CONFIRM_ADD_USER = "➕ Выдать доступ"
    CONFIRM_REMOVE_USER = "➖ Удалить доступ"
    CANCEL_ADMIN_ACTION = "✖️ Отмена"
