"""actualization migration

Revision ID: 40e630436877
Revises: 5f0b5ef6d2e1
Create Date: 2026-06-18 05:22:25.390682

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "40e630436877"
down_revision: str | Sequence[str] | None = "5f0b5ef6d2e1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

USER_STATE_ENUM_NAME = "userstate"
USER_STATE_ENUM_VALUES = (
    "WAITING_SIGNATURE_UPLOAD",
    "WAITING_PROFILE_TEMPLATE_UPLOAD",
    "WAITING_BANK_CONFIRMATION_UPLOAD",
    "WAITING_INVOICE_AMOUNT",
    "WAITING_CONVERSION_AMOUNT",
    "WAITING_NEW_USER_ID",
    "WAITING_NEW_USER_CONFIRMATION",
    "WAIT_CONFIRM_ADD_USER",
    "WAITING_REMOVE_USER_ID",
    "WAIT_CONFIRM_REMOVE_USER",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("app_events", "severity", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("app_events", "event_type", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("app_events", "details", existing_type=sa.VARCHAR(), type_=sa.Text(), existing_nullable=True)
    op.create_index(op.f("ix_app_events_created_at"), "app_events", ["created_at"], unique=False)
    op.create_index(op.f("ix_app_events_event_type"), "app_events", ["event_type"], unique=False)
    op.create_index(op.f("ix_app_events_severity"), "app_events", ["severity"], unique=False)
    op.execute(
        sa.text(
            "DO $$ BEGIN "
            f"IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = '{USER_STATE_ENUM_NAME}') THEN "
            f"CREATE TYPE {USER_STATE_ENUM_NAME} AS ENUM ({', '.join(repr(value) for value in USER_STATE_ENUM_VALUES)}); "
            "END IF; "
            "END $$;"
        )
    )
    op.alter_column(
        "user_state_storage",
        "state",
        existing_type=sa.VARCHAR(length=31),
        type_=sa.Enum(*USER_STATE_ENUM_VALUES, name=USER_STATE_ENUM_NAME),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_state_storage",
        "state",
        existing_type=sa.Enum(*USER_STATE_ENUM_VALUES, name=USER_STATE_ENUM_NAME),
        type_=sa.VARCHAR(length=31),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_app_events_severity"), table_name="app_events")
    op.drop_index(op.f("ix_app_events_event_type"), table_name="app_events")
    op.drop_index(op.f("ix_app_events_created_at"), table_name="app_events")
    op.alter_column("app_events", "details", existing_type=sa.Text(), type_=sa.VARCHAR(), existing_nullable=True)
    op.alter_column("app_events", "event_type", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("app_events", "severity", existing_type=sa.VARCHAR(length=16), nullable=True)
    op.execute(sa.text(f"DROP TYPE IF EXISTS {USER_STATE_ENUM_NAME};"))
    # ### end Alembic commands ###
