"""actualization migration

Revision ID: 40e630436877
Revises: 5f0b5ef6d2e1
Create Date: 2026-06-18 05:22:25.390682

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "40e630436877"
down_revision: str | Sequence[str] | None = "5f0b5ef6d2e1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("app_events", "severity", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("app_events", "event_type", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("app_events", "details", existing_type=sa.VARCHAR(), type_=sa.Text(), existing_nullable=True)
    op.create_index(op.f("ix_app_events_created_at"), "app_events", ["created_at"], unique=False)
    op.create_index(op.f("ix_app_events_event_type"), "app_events", ["event_type"], unique=False)
    op.create_index(op.f("ix_app_events_severity"), "app_events", ["severity"], unique=False)
    op.alter_column("user_state_storage", "state", existing_type=sa.VARCHAR(length=31), type_=sa.VARCHAR(length=64), existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_app_events_severity"), table_name="app_events")
    op.drop_index(op.f("ix_app_events_event_type"), table_name="app_events")
    op.drop_index(op.f("ix_app_events_created_at"), table_name="app_events")
    op.alter_column("app_events", "details", existing_type=sa.Text(), type_=sa.VARCHAR(), existing_nullable=True)
    op.alter_column("app_events", "event_type", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("app_events", "severity", existing_type=sa.VARCHAR(length=16), nullable=True)
    op.alter_column("user_state_storage", "state", existing_type=sa.VARCHAR(length=64), type_=sa.VARCHAR(length=31), existing_nullable=False)
    # ### end Alembic commands ###
