"""telegram ids bigint

Revision ID: a63372892e58
Revises: 63b9793230cc
Create Date: 2026-06-16 07:25:18.391742

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a63372892e58"
down_revision: str | Sequence[str] | None = "63b9793230cc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("allowed_users", "telegram_id", existing_type=sa.INTEGER(), type_=sa.BIGINT(), existing_nullable=False, autoincrement=True)
    op.alter_column("audit_log", "telegram_id", existing_type=sa.INTEGER(), type_=sa.BIGINT(), existing_nullable=False)
    op.alter_column("bank_account", "owner_telegram_id", existing_type=sa.INTEGER(), type_=sa.BIGINT(), existing_nullable=False)
    op.alter_column("company_profile", "owner_telegram_id", existing_type=sa.INTEGER(), type_=sa.BIGINT(), existing_nullable=False)
    op.alter_column("document_generation_history", "telegram_id", existing_type=sa.INTEGER(), type_=sa.BIGINT(), existing_nullable=True)
    op.alter_column("gmail_account", "owner_telegram_id", existing_type=sa.INTEGER(), type_=sa.BIGINT(), existing_nullable=False)
    op.alter_column("known_users", "telegram_id", existing_type=sa.INTEGER(), type_=sa.BIGINT(), existing_nullable=False, autoincrement=True)
    op.alter_column("oauth_sessions", "telegram_id", existing_type=sa.INTEGER(), type_=sa.BIGINT(), existing_nullable=False)
    op.alter_column("signatures", "owner_telegram_id", existing_type=sa.INTEGER(), type_=sa.BIGINT(), existing_nullable=False)
    op.alter_column("user_config", "telegram_id", existing_type=sa.INTEGER(), type_=sa.BIGINT(), existing_nullable=False, autoincrement=True)
    op.alter_column("user_state_storage", "owner_telegram_id", existing_type=sa.INTEGER(), type_=sa.BIGINT(), existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user_state_storage", "owner_telegram_id", existing_type=sa.BIGINT(), type_=sa.INTEGER(), existing_nullable=False)
    op.alter_column("user_config", "telegram_id", existing_type=sa.BIGINT(), type_=sa.INTEGER(), existing_nullable=False, autoincrement=True)
    op.alter_column("signatures", "owner_telegram_id", existing_type=sa.BIGINT(), type_=sa.INTEGER(), existing_nullable=False)
    op.alter_column("oauth_sessions", "telegram_id", existing_type=sa.BIGINT(), type_=sa.INTEGER(), existing_nullable=False)
    op.alter_column("known_users", "telegram_id", existing_type=sa.BIGINT(), type_=sa.INTEGER(), existing_nullable=False, autoincrement=True)
    op.alter_column("gmail_account", "owner_telegram_id", existing_type=sa.BIGINT(), type_=sa.INTEGER(), existing_nullable=False)
    op.alter_column("document_generation_history", "telegram_id", existing_type=sa.BIGINT(), type_=sa.INTEGER(), existing_nullable=True)
    op.alter_column("company_profile", "owner_telegram_id", existing_type=sa.BIGINT(), type_=sa.INTEGER(), existing_nullable=False)
    op.alter_column("bank_account", "owner_telegram_id", existing_type=sa.BIGINT(), type_=sa.INTEGER(), existing_nullable=False)
    op.alter_column("audit_log", "telegram_id", existing_type=sa.BIGINT(), type_=sa.INTEGER(), existing_nullable=False)
    op.alter_column("allowed_users", "telegram_id", existing_type=sa.BIGINT(), type_=sa.INTEGER(), existing_nullable=False, autoincrement=True)
    # ### end Alembic commands ###
