"""add gmail account

Revision ID: e05c13c6dd2a
Revises: 88244613a42f
Create Date: 2026-06-13 17:25:24.309630

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e05c13c6dd2a"
down_revision: str | Sequence[str] | None = "88244613a42f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gmail_account",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("owner_telegram_id", sa.Integer(), nullable=False),
        sa.Column("gmail_email", sa.String(), nullable=True),
        sa.Column("gmail_refresh_token", sa.String(), nullable=True),
        sa.Column("gmail_connected_at", sa.DateTime(), nullable=True),
        sa.Column("gmail_last_error", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_gmail_account_owner_telegram_id"), "gmail_account", ["owner_telegram_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_gmail_account_owner_telegram_id"), table_name="gmail_account")
    op.drop_table("gmail_account")
    # ### end Alembic commands ###
