name: ⏰ Generate Invoice

on:
  workflow_dispatch:

jobs:
  invoice:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      ACCOUNT_HOLDER: ${{ secrets.ACCOUNT_HOLDER }}
      ACCOUNT_HOLDER_ADDRESS: ${{ secrets.ACCOUNT_HOLDER_ADDRESS }}
      ACCOUNT_BIC: ${{ secrets.ACCOUNT_BIC }}
      ACCOUNT_IBAN: ${{ secrets.ACCOUNT_IBAN }}
      ACCOUNT_NUMBER: ${{ secrets.ACCOUNT_NUMBER }}
      BANK_NAME: ${{ secrets.BANK_NAME }}
      COMPANY_NAME: ${{ secrets.COMPANY_NAME }}
      COMPANY_ADDRESS: ${{ secrets.COMPANY_ADDRESS }}
      INVOICE_AMOUNT: ${{ secrets.INVOICE_AMOUNT }}
      SERVICE_AGREEMENT_DATE: ${{ secrets.SERVICE_AGREEMENT_DATE }}
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Install LibreOffice
        run: |
          sudo apt-get update
          sudo apt-get install -y libreoffice

      - name: Generate and send invoice
        run: |
          poetry run python -m src.workflows.generate_invoice_and_send
          curl -X POST \
            "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d text="✅ Finpipe invoice generation success"

      - name: Invoice Failed Report
        if: failure()
        run: |
          curl -X POST \
            "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d text="❌ Finpipe invoice generation failed"
